// This file has been autogenerated from a class added in the UI designer.

using System;
using FirstBrick.iOS.Views.Base;
using FirstBrick.ViewModels.ViewModels.Onboarding;
using MvvmCross.Platforms.Ios.Presenters.Attributes;
using MvvmCross.Platforms.Ios.Views;
using UIKit;

namespace FirstBrick.iOS.Views
{
	[MvxFromStoryboard("Core")]
    [MvxRootPresentation]
	public partial class SplashscreenViewController : BaseViewController<SplashscreenViewModel>
	{
        public SplashscreenViewController(IntPtr handle) : base(handle)
        {
            
        }
	}
}
